### ISSUE TITLE
crash issiue during tap outside the dialogs

### ISSUE THREAD

**Issue by capaccio** [OpenGeeksMe/Android-File-Chooser#10]
I tested the demo app and everithing is cool, I found just 2 issues:

1) on android 7 when it prompt (camera or documents) it crash if I tap outside the dialog box
2) on android 4.4.2 the app runs but file dialogs does not appears 

Thanks Giorgio

**Comment by sabrimev** [comment]
The same for me. It crashes.

**Comment by DanielLe232** [comment]
I think you miss permission.
and about if you come back, you could change

if (data != null || mCameraPhotoPath != null) {
Integer count = 1;//old
ClipData images = null;
try { ............
the Integer count = 1; from 1 to 0
Integer count = 0;//change new

**Comment by sputn1k** [comment]
> the Integer count = 1; from 1 to 0

thanks that worked for me cheers

**Comment by floryn90** [comment]
I integrated your solution and i'm closing the issue
