### ISSUE TITLE
Not showing camera option

### ISSUE THREAD

**Issue by m35ka** [OpenGeeksMe/Android-File-Chooser#3]
Hey there, 

Thanks for sharing this. I've been trying to get this working for ages and then came across your blog. Really pleased. 

However when I click the "Add photos" button in my website through webview it takes me straight to the gallery and doesn't give me an option to use the camera, it does however if I access the website from the chrome browser. 

Any ideas how I can fix this? 

Thanks again

**Comment by floryn90** [comment]
Hi! Can you tell me what's your Android version that you are using?

**Comment by m35ka** [comment]
Hey thanks for responding. I was using 23 but Ive change to 22 now and its
working fine.

Thanks again
