### ISSUE TITLE
Other file types 

### ISSUE THREAD

**Issue by zhkuskov** [OpenGeeksMe/Android-File-Chooser#5]
Hi,
Thanks for your example - it works fine.
Can you help - how implement downloading all types of files?
Thank you!

**Comment by floryn90** [comment]
Try to change image/* with */* on line 187 on MainActivity.java  https://github.com/OpenGeeksMe/Android-File-Chooser/blob/master/app/src/main/java/it/floryn90/webapp/MainActivity.java#L187
If you have some problems, tell me!

**Comment by zhkuskov** [comment]
Or, thank you!
It works.
