### ISSUE TITLE
Failed to click Cancel button

### ISSUE THREAD

**Issue by iron-zorin** [OpenGeeksMe/Android-File-Chooser#7]
Open app, click "START UPLOADING"
![select image](https://user-images.githubusercontent.com/26596888/29283798-e12cda90-8130-11e7-8f06-7479b769d6ed.jpg)

Click "Cancel" or press "Back button" on device"

![sorry webapp](https://user-images.githubusercontent.com/26596888/29283810-e5bec64a-8130-11e7-8d4d-e294a4ad679b.jpg)

[LeEco Le 2](http://www.devicespecifications.com/en/model/77103b83)
Android 6.0

**Comment by fgeorgi** [comment]
You can fix this very easily

Just change:

if (data != null || mCameraPhotoPath != null) {
            Integer count = 1;
            ClipData images = null;
            try { ............

the Integer count = 1; from 1 to 0

Integer count = 0;

done;
