### ISSUE TITLE
Missing permission 

### ISSUE THREAD

**Issue by openmotion** [OpenGeeksMe/Android-File-Chooser#8]
hello
your solution is great ! but you don't include the verifyStoragePermissions
i added this function
 
    public static void verifyStoragePermissions(Activity activity) {
        // Check if we have read or write permission
        int writePermission = ActivityCompat.checkSelfPermission(activity, Manifest.permission.WRITE_EXTERNAL_STORAGE);
        int readPermission = ActivityCompat.checkSelfPermission(activity, Manifest.permission.READ_EXTERNAL_STORAGE);

        if (writePermission != PackageManager.PERMISSION_GRANTED || readPermission != PackageManager.PERMISSION_GRANTED) {
            // We don't have permission so prompt the user
            ActivityCompat.requestPermissions(
                    activity,
                    PERMISSIONS_STORAGE,
                    REQUEST_EXTERNAL_STORAGE
            );
        }
    }

with this variables
    // Storage Permissions variables
    private static final int REQUEST_EXTERNAL_STORAGE = 1;
    private static String[] PERMISSIONS_STORAGE = {
            Manifest.permission.READ_EXTERNAL_STORAGE,
            Manifest.permission.WRITE_EXTERNAL_STORAGE
    };

and in on create
verifyStoragePermissions(this);

**Comment by JosephM3388** [comment]
Isn't this required for Marshmellow and up?

**Comment by floryn90** [comment]
integrated @openmotion solution
